version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    environment:
      FLASK_APP: src/app.py
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: