version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - app_data:/app/data
    environment:
      FLASK_APP: src/app.py
      FLASK_ENV: production
      SECRET_KEY: your-production-secret-key

volumes:
  app_data: