apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: islamic-app-metrics
  namespace: islamic-app
  labels:
    app: islamic-flask-app
spec:
  selector:
    matchLabels:
      app: islamic-flask-app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: islamic-app-metrics
  namespace: islamic-app
  labels:
    app: islamic-flask-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: islamic-flask-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: islamic-app
  labels:
    app: islamic-flask-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "islamic_app_rules.yml"
    
    scrape_configs:
      - job_name: 'islamic-flask-app'
        static_configs:
          - targets: ['islamic-app-service:5000']
        metrics_path: /metrics
        scrape_interval: 30s
        
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - islamic-app
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            
  islamic_app_rules.yml: |
    groups:
      - name: islamic_app_alerts
        rules:
          - alert: HighCPUUsage
            expr: rate(container_cpu_usage_seconds_total{pod=~"islamic-app-deployment-.*"}[5m]) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "Pod {{ $labels.pod }} has been using more than 80% CPU for more than 5 minutes"
              
          - alert: HighMemoryUsage
            expr: container_memory_usage_bytes{pod=~"islamic-app-deployment-.*"} / container_spec_memory_limit_bytes > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Pod {{ $labels.pod }} is using more than 90% of allocated memory"
              
          - alert: PodRestartCount
            expr: increase(kube_pod_container_status_restarts_total{namespace="islamic-app"}[1h]) > 3
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: "Pod restarting frequently"
              description: "Pod {{ $labels.pod }} has restarted more than 3 times in the last hour"
