apiVersion: v1
kind: PersistentVolume
metadata:
  name: islamic-app-pv
  labels:
    app: islamic-flask-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/islamic-app
    type: DirectoryOrCreate
