apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: islamic-app-pvc
  namespace: islamic-app
  labels:
    app: islamic-flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
