apiVersion: v1
kind: ServiceAccount
metadata:
  name: islamic-app-sa
  namespace: islamic-app
  labels:
    app: islamic-flask-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: islamic-app-role
  namespace: islamic-app
  labels:
    app: islamic-flask-app
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: islamic-app-rolebinding
  namespace: islamic-app
  labels:
    app: islamic-flask-app
subjects:
- kind: ServiceAccount
  name: islamic-app-sa
  namespace: islamic-app
roleRef:
  kind: Role
  name: islamic-app-role
  apiGroup: rbac.authorization.k8s.io
